library(data.table)
library(ggplot2)
library(ggthemes)
library(magrittr)
library(Metrics)
library(olsrr)
library(patchwork)
library(quantreg)
library(readxl)
library(rgdal)
library(rprojroot)
library(rworldmap)
library(scales)
library(sf)
library(stringr)


rootdir <- find_root(has_dir("src"))
resdir <- file.path(rootdir, "results")
datadir <- file.path(rootdir, "data")
figdir <- file.path(resdir, 'figures')
if (!(dir.exists(figdir))) dir.create(figdir)
